version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "waveform-generator"
s3_bucket = "hippo-waveforms-sam"
s3_prefix = "waveform-generator"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
