AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  waveforms

  Generates PNG of the waveform of a .wav file

Globals:
  Function:
    Timeout: 10

Resources:
  WaveformsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::166605477498:role/service-role/access-s3
      MemorySize: 512 # somewhat memory intensive operations
      Architectures:
        - x86_64
      EventInvokeConfig:
        MaximumRetryAttempts: 0 # default was 2
      Environment:
        Variables:
          MPLCONFIGDIR: /tmp # otherwise matplotlib complains it can't open a writable config directory

Outputs:
  WaveformsFunction:
    Description: "Waveforms Lambda Function ARN"
    Value: !GetAtt WaveformsFunction.Arn
