version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
  post_build:
    commands:
      - echo Build completed on `date`
        # - ARTIFACT_VERSION=`cat src/main/resources/cogbog/discord/version.txt`
        # - aws s3api put-object-tagging --key artifacts/build/libs/hippokleides-glory-horse-uber.jar --bucket hippokleides-cicd --tagging "{\"TagSet\": [{\"Key\": \"version\", \"Value\": \"$ARTIFACT_VERSION\"}]}"
artifacts:
  files:
    - build/libs/hippokleides-glory-horse-uber.jar
