version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "recordings-rest"
s3_prefix = "recordings-rest"
s3_bucket = "hippo-trimmer-sam"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
